version: "3.8"
services:
  my_blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql:latest
    container_name: my_blog
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: x
      MYSQL_DATABASE: x
      MYSQL_USER: x
      MYSQL_PASSWORD: x
    ports:
      - "3307:3307"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: my_blog
    depends_on:
      - my_blog
    ports:
      - "8181:80"